version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 135246aA@
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"


  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - minio
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bookingroom
      #      - SPRING_DATASOURCE_URL=jdbc:mysql://103.148.57.233:3306/bookingroom
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=nhanbn98
      - SPRING_MINIO_HOST=http://127.0.0.1:9000
      - SPRING_MINIO_ACCESS_KEY=admin
      - SPRING_MINIO_SECRET_KEY=135246aA@
      - SPRING_MINIO_SECURE=false
      - SPRING_MINIO_BUCKET_NAME=bookingroom
      - SPRING_MINIO_IMAGE_SIZE=10485760
      - SPRING_MINIO_FILE_SIZE=1073741824
      - SPRING_BUCKET_NAME_HOTEL=hotel
      - SPRING_BUCKET_NAME_ROOM=imagesroom
    # Đặt biến môi trường dựa trên môi trường Docker