server:
#  port: 80
  servlet:
    context-path: /
#  address: 192.168.1.11


#spring-hibernate for mysql
spring:
  #  profiles:
  #    active: heroku
  main:
    allow-circular-references: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  #    properties:

  #connection MySQL
  datasource:
#    url: jdbc:mysql://localhost:3306/booking_room?useUnicode=yes&characterEncoding=UTF-8
#    username: root
#    password: 135246aA@

    url: jdbc:mysql://sql.freedb.tech:3306/freedb_db_booking
    username: freedb_nhannguyen
    password: XRHayk%&eV4&2#K

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

