server:
  port: 80
  servlet:
    context-path: /
#  address: 192.168.1.11


#spring-hibernate for mysql
spring:
  #  profiles:
  #    active: heroku
  main:
    allow-circular-references: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  #    properties:

  #connection MySQL
  datasource:
#    url: jdbc:mysql://localhost:3306/booking_room?useUnicode=yes&characterEncoding=UTF-8
#    username: root
#    password: nhanbn98
#    driverClassName: com.mysql.jdbc.Driver

#    url: jdbc:mysql://sql.freedb.tech:3306/freedb_db_booking
#    username: freedb_nhannguyen
#    password: XRHayk%&eV4&2#K

    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://103.148.57.233:3306/bookingroom}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:nhanbn98}
    driver-class-name: com.mysql.jdbc.Driver

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

minio:
  endpoint: ${SPRING_MINIO_HOST:http://103.148.57.233:9000}
  port: 9000
  accessKey:  ${SPRING_MINIO_ACCESS_KEY:admin} #Login Account
  secretKey:  ${SPRING_MINIO_SECRET_KEY:135246aA@} # Login Password
  secure: ${SPRING_MINIO_SECURE:false}
  bucket-name: ${SPRING_MINIO_BUCKET_NAME:bookingroom} # Bucket Name
  image-size: ${SPRING_MINIO_IMAGE_SIZE:10485760} #  Maximum size of picture file
  file-size: ${SPRING_MINIO_FILE_SIZE:1073741824} #  Maximum file size

bucket-name:
  hotel: ${SPRING_BUCKET_NAME_HOTEL:hotel}
  room: ${SPRING_BUCKET_NAME_ROOM:imagesroom}